services:
  ros:
    container_name: ros
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY=host.docker.internal:0
      - LIBGL_ALWAYS_INDIRECT=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host # for using localhost without port mapping
    command: bash -c "roscore"
